# Generated by Django 4.1.7 on 2024-09-03 02:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('familyComposition', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.CharField(default=0, max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('cstat', models.CharField(max_length=10)),
                ('relation_to_patient', models.CharField(max_length=10)),
                ('hea', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MSSAT',
            fields=[
                ('mssat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doac', models.CharField(max_length=50)),
                ('venue', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('basic_ward', models.CharField(default='NONE', max_length=50)),
                ('non_basic', models.CharField(default='NONE', max_length=50)),
                ('mss_no', models.CharField(max_length=50)),
                ('tla', models.CharField(max_length=50)),
                ('src_referal_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('cnum', models.CharField(max_length=20)),
                ('employer', models.CharField(default='NONE', max_length=100)),
                ('phil_mem', models.CharField(max_length=20)),
                ('mswd_cassif', models.CharField(max_length=30)),
                ('marginalized_sec_mem', models.CharField(max_length=50)),
                ('fuel_source', models.CharField(max_length=100)),
                ('amt_fuel_source', models.CharField(default=[0, 0, 0, 0], max_length=30)),
                ('clothing_amt', models.CharField(max_length=10)),
                ('duration_of_prob', models.CharField(max_length=100)),
                ('prev_treatment', models.CharField(max_length=100)),
                ('health_accessibility_prob', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SCP',
            fields=[
                ('scp', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psychosocial_assessment', models.CharField(max_length=1500)),
                ('reccomendation_for_oth_member', models.CharField(max_length=250)),
                ('mssat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.mssat')),
            ],
        ),
        migrations.CreateModel(
            name='UIS',
            fields=[
                ('uis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('hospno', models.CharField(max_length=30)),
                ('phil_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UIS_copy',
            fields=[
                ('uis_copy', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uis_excel', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UIS_misc',
            fields=[
                ('uis_misc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_income', models.CharField(default=0, max_length=20)),
                ('total_expense', models.CharField(default=0, max_length=20)),
                ('category', models.CharField(default='?', max_length=10)),
                ('toe', models.CharField(max_length=25)),
                ('householdsize', models.CharField(default=0, max_length=5)),
                ('total_amount_of_assistance', models.CharField(default=0, max_length=20)),
                ('swo', models.CharField(default='N/A', max_length=50)),
                ('has_mssat', models.BooleanField(default=False)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='SWA',
            fields=[
                ('swa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swa_desc', models.CharField(max_length=1500)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
                ('uis_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc')),
            ],
        ),
        migrations.CreateModel(
            name='scp_table',
            fields=[
                ('scp_table', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=60)),
                ('problem_need', models.CharField(max_length=250)),
                ('goals_objective', models.CharField(max_length=250)),
                ('treatment_intervention', models.CharField(max_length=250)),
                ('frequency_duration', models.CharField(max_length=250)),
                ('responsible_person', models.CharField(max_length=250)),
                ('expected_output', models.CharField(max_length=250)),
                ('scp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.scp')),
            ],
        ),
        migrations.AddField(
            model_name='scp',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AddField(
            model_name='scp',
            name='uis_misc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc'),
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommendation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_assistance', models.CharField(max_length=50)),
                ('amt_of_assistance', models.CharField(max_length=25)),
                ('mode_of_assistance', models.CharField(max_length=25)),
                ('fund_source', models.CharField(max_length=15)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
                ('uis_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPresented',
            fields=[
                ('problemPresented', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=250)),
                ('prob_desc', models.CharField(max_length=250)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
                ('uis_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc')),
            ],
        ),
        migrations.AddField(
            model_name='mssat',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AddField(
            model_name='mssat',
            name='uis_misc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc'),
        ),
        migrations.CreateModel(
            name='ListofExpenses',
            fields=[
                ('listofExpenses', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=20)),
                ('amt_house', models.CharField(max_length=10)),
                ('lot', models.CharField(max_length=20)),
                ('amt_lot', models.CharField(max_length=10)),
                ('ligth_source', models.CharField(max_length=100)),
                ('amt_ligth_source', models.CharField(max_length=50)),
                ('water_source', models.CharField(max_length=100)),
                ('amt_water_source', models.CharField(max_length=50)),
                ('other_expenses', models.CharField(max_length=150)),
                ('amt_other_expenses', models.CharField(max_length=70)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
                ('uis_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc')),
            ],
        ),
        migrations.CreateModel(
            name='Informant',
            fields=[
                ('informant', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_intake', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('time_of_interview', models.CharField(max_length=15)),
                ('end_time_of_interview', models.CharField(max_length=15)),
                ('relation_to_patient', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=30)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
                ('uis_misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis_misc')),
            ],
        ),
        migrations.CreateModel(
            name='IdentifyingInformation',
            fields=[
                ('identifyingInformation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('pob', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(max_length=150)),
                ('present_address', models.CharField(max_length=150)),
                ('cstat', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=20)),
                ('hea', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=10)),
                ('patient_type', models.CharField(max_length=10)),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
            ],
        ),
        migrations.CreateModel(
            name='Fc_other_source',
            fields=[
                ('fc_other_source', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otherSources_of_fi_desc', models.CharField(max_length=100)),
                ('otherSources_of_fi', models.CharField(max_length=15)),
                ('familyComposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.familycomposition')),
                ('uis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis')),
            ],
        ),
        migrations.AddField(
            model_name='familycomposition',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
    ]
