# Generated by Django 5.0.6 on 2024-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informant',
            name='end_time_of_interview',
            field=models.CharField(default='12:00', max_length=10),
        ),
        migrations.AddField(
            model_name='mssat',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mssat',
            name='venue',
            field=models.CharField(default='', max_length=50),
        ),
    ]
