# Generated by Django 5.0.6 on 2024-07-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uis', '0002_informant_end_time_of_interview_mssat_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mssat',
            name='basic_ward',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='mssat',
            name='non_basic',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
