# Generated by Django 5.0.6 on 2024-07-07 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uis', '0003_alter_mssat_basic_ward_alter_mssat_non_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycomposition',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='fc_other_source',
            name='familyComposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.familycomposition'),
        ),
        migrations.AlterField(
            model_name='fc_other_source',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='informant',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='listofexpenses',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='mssat',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='problempresented',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='scsr',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
        migrations.AlterField(
            model_name='swa',
            name='uis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uis.uis'),
        ),
    ]
