# Generated by Django 5.0.6 on 2024-07-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uis', '0004_alter_familycomposition_uis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='end_time_of_interview',
            field=models.CharField(default='12:00', max_length=15),
        ),
        migrations.AlterField(
            model_name='informant',
            name='time_of_interview',
            field=models.CharField(max_length=15),
        ),
    ]
